name: cd

on:
  workflow_dispatch:
  push:
    tags: 
      - "*.*.*"

permissions:
  id-token: write
  
jobs:
  npm: 
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@master
      -
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      -
        run: |
          npm run build
      - 
        working-directory: ./dist
        run: |
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
